### ISSUE TITLE
Error in create-vod-hls.sh file

### ISSUE THREAD

**Issue by abhishekraj272** [pluginfactory/HLS-transcoding-nodejs#2]
Getting syntax error.

**Comment by abhishekraj272** [comment]
Sorted

**Comment by gauravsharmadev** [comment]
@abhishekraj272 what was the issue. If you can mention and how did you fix it. It might help someone.

**Comment by abhishekraj272** [comment]
@gauravsharmadev  In the usage you have written SOURCE_NAME and OUTPUT,
But It accepts 2 params 

1. Input File location w/o extension
2. Input file extension
